[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "brain_tumor_detector"
version = "0.1.0"
dependencies = ["torch", "torchvision", "numpy", "matplotlib", "scikit-learn", "kagglehub", "tqdm", "huggingface_hub", "voila", "pillow", "ipywidgets>=8.0.0", "solara"]

[tool.setuptools.packages.find]
where = ["."]