[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "brain_tumor_detector"
version = "0.1.0"
dependencies = ["torch", "torchvision", "numpy", "matplotlib", "pathlib", "scikit-learn", "kagglehub", "shutil", "tqdm"]

[tool.setuptools.packages.find]
where = ["."]